- name: Monitor Image Creation
  hosts: all
  strategy: free
  tasks:


    - name: Get Image Creation info
      uri:
        url: "{{ service_url }}/build/{{ TOSCA_JOB_ID }}"
        validate_certs: "{{ insecure_tls | ternary('no', 'yes', 'yes') }}"
        method: GET
        headers:
          Accept: application/json
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        return_content: yes
      register: get_response
      no_log: "{{ debug_logs | default('false') == 'false' }}"

    - name: Extract content
      set_fact:
        content: "{{ get_response.content | from_json }}"
      no_log: "{{ debug_logs | default('false') == 'false' }}"

    - name: Extract TOSCA_JOB_STATUS
      set_fact:
        TOSCA_JOB_STATUS: "{{ content.status | upper }}"
        filename: ""

    - name: Display image status
      debug:
        msg: "Image creation status: {{ TOSCA_JOB_STATUS }}"

    - name: Fix TOSCA_JOB_STATUS for success
      set_fact:
        TOSCA_JOB_STATUS: "COMPLETED"
        filename: "{{ content.filename }}"
      when:
        - TOSCA_JOB_STATUS == "FINISHED"