tosca_definitions_version: alien_dsl_3_0_0

metadata:
  template_name: imagecreation.ansible
  template_version: 1.3.0-SNAPSHOT
  template_author: loicalbertin


imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - alien-base-types:3.0.0
  - yorc-types:1.1.0
  - eflows4hpc.env:1.1.0

data_types:
  imagecreation.ansible.datatypes.Machine:
    derived_from: tosca.datatypes.Root
    properties:
      platform:
        type: string
        required: true
      architecture:
        type: string
        required: true
      container_engine:
        type: string
        required: true
      mpi:
        type: string
        required: true
      gpu:
        type: string
        required: true

node_types:
  imagecreation.ansible.nodes.ImageCreation:
    derived_from: org.alien4cloud.nodes.Job
    metadata:
      icon: icons/cargo.png
    properties:
      service_url:
        type: string
        required: true
      insecure_tls:
        type: boolean
        required: false
        default: false
      username:
        type: string
        required: true
      password:
        type: string
        required: true
      machine:
        type: imagecreation.ansible.datatypes.Machine
        required: true
      workflow:
        type: string
        required: true
      step_id:
        type: string
        required: true
      force:
        type: boolean
        required: false
        default: false
      debug:
        type: boolean
        description: Do not redact sensible information on logs
        default: false
      run_in_standard_mode:
        type: boolean
        required: false
        default: true
    attributes:
      filename_run: { get_operation_output: [ SELF, tosca.interfaces.node.lifecycle.Runnable, run, filename ] }
      filename_start: { get_operation_output: [ SELF, Standard, start, filename ] }
    requirements:
      - environment:
          capability: eflows4hpc.env.capabilities.ExecutionEnvironment
          relationship: tosca.relationships.DependsOn
          occurrences: [ 0, UNBOUNDED ]
    interfaces:
      Standard:
        inputs:
          run_in_standard_mode: { get_property: [ SELF, run_in_standard_mode ] }
          service_url: { get_property: [ SELF, service_url ] }
          insecure_tls: { get_property: [ SELF, insecure_tls ] }
          debug_logs: { get_property: [ SELF, debug ] }
          username: { get_property: [ SELF, username ] }
          password: { get_property: [ SELF, password ] }

        start:
          inputs:
            machine: { get_property: [ SELF, machine ] }
            workflow: { get_property: [ SELF, workflow ] }
            step_id: { get_property: [ SELF, step_id ] }
            force: { get_property: [ SELF, force ] }
            machine_platform_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_platform] }
            machine_architecture_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_architecture] }
            machine_container_engine_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_container_engine] }
            machine_mpi_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_mpi] }
            machine_gpu_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_gpu] }
          implementation: playbooks/start_in_standard_mode.yaml

      tosca.interfaces.node.lifecycle.Runnable:
        inputs:
          service_url: { get_property: [ SELF, service_url ] }
          insecure_tls: { get_property: [ SELF, insecure_tls ] }
          debug_logs: { get_property: [ SELF, debug ] }
          username: { get_property: [ SELF, username ] }
          password: { get_property: [ SELF, password ] }
        submit:
          inputs:
            machine: { get_property: [ SELF, machine ] }
            workflow: { get_property: [ SELF, workflow ] }
            step_id: { get_property: [ SELF, step_id ] }
            force: { get_property: [ SELF, force ] }
            machine_platform_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_platform] }
            machine_architecture_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_architecture] }
            machine_container_engine_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_container_engine] }
            machine_mpi_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_mpi] }
            machine_gpu_from_env: { get_attribute: [ REQ_TARGET, environment, image_creation_machine_gpu] }
          implementation: playbooks/submit_imagecreation.yaml
        run:
          implementation: playbooks/monitor_imagecreation.yaml
